dist: xenial

language: python

python:
  - 2.7
  - 3.6
  - 3.7

cache: pip

env:
  - DJANGO_VERSION=2.0.x
  - DJANGO_VERSION=2.1.x
  - DJANGO_VERSION=1.11.x

matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=2.0.x
    - python: 2.7
      env: DJANGO_VERSION=2.1.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"
